import type { ValidationCase } from "@/lib/validation/types";

function id(suffix: string): string {
  return `default_${suffix}`;
}

export const DEFAULT_VALIDATION_CASES: ValidationCase[] = [
  {
    id: id("google_no_pii"),
    name: "공개 Google Forms 개인정보 없음",
    url: "https://docs.google.com/forms/d/e/PLACEHOLDER/viewform",
    platformGroup: "google_forms",
    expectedPlatform: "google_forms",
    expectedExtractor: "GoogleFormsExtractor",
    expectedMinQuestionCount: 1,
    expectedDetectedCategories: [],
    expectedIsLimited: false,
    notes: "실제 공개 Google Forms URL로 교체 후 enabled=true",
    enabled: false,
  },
  {
    id: id("google_name_contact"),
    name: "공개 Google Forms 이름/연락처 수집",
    url: "https://docs.google.com/forms/d/e/PLACEHOLDER/viewform",
    platformGroup: "google_forms",
    expectedPlatform: "google_forms",
    expectedExtractor: "GoogleFormsExtractor",
    expectedMinQuestionCount: 2,
    expectedDetectedCategories: ["name", "phone"],
    expectedRiskGrade: "risk",
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("google_privacy_notice"),
    name: "공개 Google Forms 개인정보 고지문 포함",
    url: "https://docs.google.com/forms/d/e/PLACEHOLDER/viewform",
    platformGroup: "google_forms",
    expectedPlatform: "google_forms",
    expectedExtractor: "GoogleFormsExtractor",
    expectedMinQuestionCount: 1,
    expectedIsLimited: false,
    notes: "고지문이 있으면 notice 누락 finding이 과도하지 않은지 확인",
    enabled: false,
  },
  {
    id: id("naver_quasi"),
    name: "네이버폼 성별/연령/거주지역 설문",
    url: "https://form.naver.com/PLACEHOLDER",
    platformGroup: "naver_forms",
    expectedPlatform: "naver_forms",
    expectedExtractor: "NaverFormsExtractor",
    expectedMinQuestionCount: 3,
    expectedDetectedCategories: ["quasi_identifier"],
    expectedDataLevel: "D2",
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("naver_event"),
    name: "네이버폼 이름/연락처 이벤트 설문",
    url: "https://form.naver.com/PLACEHOLDER",
    platformGroup: "naver_forms",
    expectedPlatform: "naver_forms",
    expectedExtractor: "NaverFormsExtractor",
    expectedMinQuestionCount: 2,
    expectedDetectedCategories: ["name", "phone"],
    expectedContext: "event",
    expectedDataLevel: "D3",
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("moaform_consent"),
    name: "모아폼 개인정보 동의 포함 설문",
    url: "https://www.moaform.com/q/PLACEHOLDER",
    platformGroup: "moaform",
    expectedPlatform: "moaform",
    expectedExtractor: "MoaformExtractor",
    expectedMinQuestionCount: 1,
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("moaform_employee603"),
    name: "모아폼 직원 고충 설문",
    url: "https://www.moaform.com/q/PLACEHOLDER",
    platformGroup: "moaform",
    expectedPlatform: "moaform",
    expectedExtractor: "MoaformExtractor",
    expectedMinQuestionCount: 3,
    expectedContext: "employee",
    expectedDetectedCategories: ["sensitive_complaint"],
    expectedDataLevel: "D4",
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("generic_html"),
    name: "일반 HTML 문의폼",
    url: "https://example.com/contact-form",
    platformGroup: "generic_html",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    expectedMinQuestionCount: 1,
    expectedIsLimited: false,
    notes: "실제 HTML form 페이지 URL로 교체",
    enabled: false,
  },
  {
    id: id("no_questions"),
    name: "문항 없는 일반 페이지",
    url: "https://example.com/about",
    platformGroup: "generic_html",
    expectedPlatform: "generic",
    expectedExtractor: "Limited",
    expectedMinQuestionCount: 0,
    expectedIsLimited: true,
    enabled: false,
  },
  {
    id: id("localhost_block"),
    name: "localhost 차단 테스트",
    url: "http://localhost:3000/test",
    platformGroup: "unknown",
    expectedPlatform: "unknown",
    expectedExtractor: "Limited",
    expectedIsLimited: true,
    notes: "URL 안전검사 차단 확인",
    enabled: true,
  },
  {
    id: id("127_block"),
    name: "127.0.0.1 차단 테스트",
    url: "http://127.0.0.1:8080/survey",
    platformGroup: "unknown",
    expectedPlatform: "unknown",
    expectedExtractor: "Limited",
    expectedIsLimited: true,
    enabled: true,
  },
  {
    id: id("file_block"),
    name: "file URL 차단 테스트",
    url: "file:///etc/passwd",
    platformGroup: "unknown",
    expectedPlatform: "unknown",
    expectedExtractor: "Limited",
    expectedIsLimited: true,
    enabled: true,
  },
  {
    id: id("walla"),
    name: "왈라 URL 테스트 후보",
    url: "https://www.walla.co.kr/survey/PLACEHOLDER",
    platformGroup: "walla",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    expectedIsLimited: false,
    enabled: false,
  },
  {
    id: id("now_survey"),
    name: "나우앤서베이 URL 테스트 후보",
    url: "https://www.nownsurvey.com/survey/PLACEHOLDER",
    platformGroup: "now_survey",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    enabled: false,
  },
  {
    id: id("survey_monkey"),
    name: "SurveyMonkey URL 테스트 후보",
    url: "https://www.surveymonkey.com/r/PLACEHOLDER",
    platformGroup: "survey_monkey",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    enabled: false,
  },
  {
    id: id("typeform"),
    name: "Typeform URL 테스트 후보",
    url: "https://form.typeform.com/to/PLACEHOLDER",
    platformGroup: "typeform",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    enabled: false,
  },
  {
    id: id("microsoft_forms"),
    name: "Microsoft Forms URL 테스트 후보",
    url: "https://forms.office.com/r/PLACEHOLDER",
    platformGroup: "microsoft_forms",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    enabled: false,
  },
  {
    id: id("qualtrics"),
    name: "Qualtrics URL 테스트 후보",
    url: "https://survey.qualtrics.com/jfe/form/PLACEHOLDER",
    platformGroup: "qualtrics",
    expectedPlatform: "generic",
    expectedExtractor: "Limited",
    expectedIsLimited: true,
    enabled: false,
  },
  {
    id: id("wiseon"),
    name: "WiseON survey URL 테스트 후보",
    url: "https://survey.wiseon.example.com/form/demo",
    platformGroup: "wiseon_survey",
    expectedPlatform: "wiseon_csap",
    expectedExtractor: "Fixture",
    expectedMinQuestionCount: 1,
    expectedIsLimited: false,
    notes: "URL에 wiseon 포함 시 fixture 경로 사용",
    enabled: true,
  },
  {
    id: id("research_custom"),
    name: "조사회사 자체 설문 URL 테스트 후보",
    url: "https://research.example.com/survey/PLACEHOLDER",
    platformGroup: "research_company_custom",
    expectedPlatform: "generic",
    expectedExtractor: "GenericHtmlExtractor",
    enabled: false,
  },
];

export function createValidationCaseId(): string {
  return `case_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}
