import type { PlatformCoverageRow } from "@/lib/validation/types";

export const PLATFORM_COVERAGE_MATRIX: PlatformCoverageRow[] = [
  {
    id: "google_forms",
    label: "Google Forms",
    platformGroup: "google_forms",
    urlDetection: "supported",
    htmlFetch: "supported",
    questionExtraction: "supported",
    piiDetection: "supported",
    noticeDetection: "partial",
    limitedHandling: "supported",
    dedicatedExtractor: "supported",
    playwrightNeeded: "not_implemented",
    priority: "P0",
  },
  {
    id: "naver_forms",
    label: "네이버폼",
    platformGroup: "naver_forms",
    urlDetection: "supported",
    htmlFetch: "supported",
    questionExtraction: "supported",
    piiDetection: "supported",
    noticeDetection: "partial",
    limitedHandling: "supported",
    dedicatedExtractor: "supported",
    playwrightNeeded: "not_implemented",
    priority: "P0",
  },
  {
    id: "moaform",
    label: "모아폼",
    platformGroup: "moaform",
    urlDetection: "supported",
    htmlFetch: "supported",
    questionExtraction: "supported",
    piiDetection: "supported",
    noticeDetection: "partial",
    limitedHandling: "supported",
    dedicatedExtractor: "supported",
    playwrightNeeded: "not_implemented",
    priority: "P0",
  },
  {
    id: "generic_html",
    label: "Generic HTML",
    platformGroup: "generic_html",
    urlDetection: "supported",
    htmlFetch: "supported",
    questionExtraction: "partial",
    piiDetection: "partial",
    noticeDetection: "partial",
    limitedHandling: "supported",
    dedicatedExtractor: "partial",
    playwrightNeeded: "not_implemented",
    priority: "P1",
  },
  {
    id: "walla",
    label: "왈라",
    platformGroup: "walla",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "generic_beta",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P2",
  },
  {
    id: "now_survey",
    label: "나우앤서베이",
    platformGroup: "now_survey",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "generic_beta",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P2",
  },
  {
    id: "survey_monkey",
    label: "SurveyMonkey",
    platformGroup: "survey_monkey",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "limited",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P2",
  },
  {
    id: "typeform",
    label: "Typeform",
    platformGroup: "typeform",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "limited",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P2",
  },
  {
    id: "microsoft_forms",
    label: "Microsoft Forms",
    platformGroup: "microsoft_forms",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "limited",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P2",
  },
  {
    id: "qualtrics",
    label: "Qualtrics",
    platformGroup: "qualtrics",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "limited",
    piiDetection: "limited",
    noticeDetection: "limited",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P3",
  },
  {
    id: "wiseon_survey",
    label: "WiseON Survey",
    platformGroup: "wiseon_survey",
    urlDetection: "partial",
    htmlFetch: "partial",
    questionExtraction: "partial",
    piiDetection: "supported",
    noticeDetection: "partial",
    limitedHandling: "supported",
    dedicatedExtractor: "partial",
    playwrightNeeded: "not_implemented",
    priority: "P2",
  },
  {
    id: "research_company_custom",
    label: "조사회사 자체 URL",
    platformGroup: "research_company_custom",
    urlDetection: "generic_beta",
    htmlFetch: "generic_beta",
    questionExtraction: "generic_beta",
    piiDetection: "generic_beta",
    noticeDetection: "generic_beta",
    limitedHandling: "supported",
    dedicatedExtractor: "not_implemented",
    playwrightNeeded: "playwright_required",
    priority: "P3",
  },
];

export const COVERAGE_STATUS_LABELS: Record<string, string> = {
  supported: "지원",
  partial: "부분지원",
  generic_beta: "Generic 베타",
  limited: "제한",
  not_implemented: "미구현",
  playwright_required: "Playwright 필요",
};

export const COVERAGE_STATUS_COLORS: Record<string, string> = {
  supported: "bg-[#edf7f1] text-[#1f6b47]",
  partial: "bg-[#fdf6e8] text-[#8a5f12]",
  generic_beta: "bg-[#f0f4ff] text-[#3b5bdb]",
  limited: "bg-[#fdf0f2] text-[#9e2a3e]",
  not_implemented: "bg-[#f3f4f6] text-[#4b5563]",
  playwright_required: "bg-[#f3e8ff] text-[#6b21a8]",
};
